name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cloud-login:
    uses: "fermyon/actions/.github/workflows/auth.yml@main"
    secrets:
      gh_username: ${{ secrets.DEV_DOCS_PREVIEW_GH_USERNAME }}
      gh_password: ${{ secrets.DEV_DOCS_PREVIEW_GH_PASSWORD }}
      gh_totp_secret: ${{ secrets.DEV_DOCS_PREVIEW_GH_TOTP_SECRET }}

  build:
    runs-on: "ubuntu-latest"
    needs: cloud-login
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install spin
        uses: engineerd/configurator@v0.0.9
        with:
          name: "spin"
          url: "https://github.com/fermyon/spin/releases/download/v0.8.0/spin-v0.8.0-linux-amd64.tar.gz"
          pathInArchive: "spin"

      - name: Install npm packages
        run: |
          npm ci

      - name: Run npm tests
        run: |
          npm test

      - name: Install bart
        run: |
          curl -LOs https://github.com/fermyon/bartholomew/releases/download/v0.3.0/bart
          chmod +x bart
          mv bart /usr/local/bin

      - name: Check Docs
        run: |
          bart check content/* && bart check content/**/*

      - name: Retrieve saved cloud token
        uses: actions/download-artifact@v3
        with:
          name: spin-fermyon-cloud-config.json
          path: /home/runner/.config/fermyon/

      - name: Spin Deploy
        run: |
          perl -i -pe "s/name = \"fermyon-developer\"/name = \"fermyon-developer-pr-${{ github.event.pull_request.number }}\"/g" spin.toml
          cat spin.toml
          spin deploy | tee deploy.log

          PREVIEW_URL=`cat deploy.log | grep bartholomew | grep http | grep wildcard | awk '{print $2}'`
          echo $PREVIEW_URL
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
          
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Your preview is available at ${{ env.PREVIEW_URL }}