name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install spin
        uses: engineerd/configurator@v0.0.8
        with:
          name: "spin"
          url: "https://github.com/fermyon/spin/releases/download/v0.6.0/spin-v0.6.0-linux-amd64.tar.gz"
          pathInArchive: "spin"

      - name: Install npm packages
        run: |
          npm ci

      - name: Run npm tests
        run: |
          npm test

      - name: Install bart
        run: |
          curl -LOs https://github.com/fermyon/bartholomew/releases/download/v0.3.0/bart
          chmod +x bart
          mv bart /usr/local/bin

      - name: Check Docs
        run: |
          bart check content/* && bart check content/**/*

  cloud-login:
    uses: "rajatjindal/actions/.github/workflows/auth.yml@fix-auth2"
    secrets:
      gh_username: ${{ secrets.DEV_DOCS_PREVIEW_GH_USERNAME }}
      gh_password: ${{ secrets.DEV_DOCS_PREVIEW_GH_PASSWORD }}
      gh_totp_secret: ${{ secrets.DEV_DOCS_PREVIEW_GH_TOTP_SECRET }}
    with:
      fermyon_deployment_env: developer-docs-preview

  preview:
    runs-on: "ubuntu-latest"
    needs: [build, cloud-login]
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve saved cloud token
        uses: actions/download-artifact@v3
        with:
          name: developer-docs-preview.json
          path: ${{ env.GITHUB_WORKSPACE }}

      - name: Deploy preview on cloud
        uses: rajatjindal/fermyon-preview-deploy@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fermyon_token_file_name: "developer-docs-preview.json"

  cleanup: 
    runs-on: ubuntu-latest
    needs: [preview]
    if: always()
    steps:
    - uses: geekyeggo/delete-artifact@v2
      if: always()
      with:
        name: developer-docs-preview.json