name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install spin
        uses: engineerd/configurator@v0.0.8
        with:
          name: "spin"
          url: "https://github.com/fermyon/spin/releases/download/v0.10.1/spin-v0.10.1-linux-amd64.tar.gz"
          pathInArchive: "spin"

      - name: Install bart
        run: |
          curl -LOs https://github.com/fermyon/bartholomew/releases/download/v0.3.0/bart
          chmod +x bart
          mv bart /usr/local/bin

      - name: Check Docs
        run: |
          bart check content/* && bart check content/**/*
      
      - name: Install npm packages
        run: |
          npm ci

      - name: Run npm tests
        run: |
          npm test