name: Cleanup Preview
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  cloud-login:
    uses: "fermyon/actions/.github/workflows/auth.yml@main"
    secrets:
      gh_username: ${{ secrets.DEV_DOCS_PREVIEW_GH_USERNAME }}
      gh_password: ${{ secrets.DEV_DOCS_PREVIEW_GH_PASSWORD }}
      gh_totp_secret: ${{ secrets.DEV_DOCS_PREVIEW_GH_TOTP_SECRET }}
    with:
      fermyon_deployment_env: developer-docs-preview

  cleanup-preview:
    runs-on: "ubuntu-latest"
    needs: [cloud-login]
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve saved cloud token
        uses: actions/download-artifact@v3
        with:
          name: developer-docs-preview.json
          path: ${{ env.GITHUB_WORKSPACE }}

      - name: Undeploy preview from cloud
        uses: rajatjindal/fermyon-preview-deploy@main
        with:
          fermyon_token_file_name: "developer-docs-preview.json"

  cleanup-token-artifact: 
    runs-on: ubuntu-latest
    needs: [undeploy-preview]
    if: always()
    steps:
    - uses: geekyeggo/delete-artifact@v2
      if: always()
      with:
        name: developer-docs-preview.json

