name: Publish
on:
  push:
    branches: [main]
  # TODO: strategy for publishing PRs (storage is free for public repos; do we need/want cleanup automation?)
  # pull_request:
  #   branches: [main]

env:
  OCI_REF_NAME: ghcr.io/${{ github.repository_owner }}/developer

jobs:
  publish:
    runs-on: ubuntu-latest
    # TODO: uncomment
    # if: ${{ github.repository_owner == 'fermyon' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install spin
        uses: engineerd/configurator@v0.0.8
        with:
          name: "spin"
          url: "https://github.com/fermyon/spin/releases/download/canary/spin-canary-linux-amd64.tar.gz"
          pathInArchive: "spin"
      
      - name: Install npm packages
        run: |
          npm ci

      # TODO: any other node-y things to do prior to publish? 'npm run styles', etc.?

      - name: Create search index
        run: |
          npm run build-index

      - name: Spin registry login
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | spin registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish Spin app - mutable tag
        run: |
          spin registry push ${{ env.OCI_REF_NAME }}:latest

      - name: Publish Spin app - immutable tag
        run: |
          spin registry push ${{ env.OCI_REF_NAME }}:${{ github.ref_name }}-${{ github.sha }}

      - name: cleanup auth dir
        if: always()
        run: |
          rm -rf /home/runner/.config/fermyon